config/routes.rb
Rails.application.routes.draw do
  root to: "developers#index"
  devise_for :users
  resources :developers do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  get 'profile/:id', to: 'pages#profile', as: 'user_profile'
  patch 'bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  patch 'bookings/:id/refuse', to: 'bookings#refuse', as: 'refuse_booking'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user
  belongs_to :developer
end

app/models/developer.rb
class Developer < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :first_name, :last_name, :description, :city, :price_per_day, presence: true
  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 1 }
  validates :description, length: { minimum: 100, maximum: 1000 }
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :developers
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  before_action :authenticate_user!

  # Pundit: allow-list approach
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:accept, :refuse]
  before_action :set_developer, only: [:new, :create]

  def new
    @booking = Booking.new
  end

  def create
    #@booking = Booking.new()
    @booking = Booking.new(
      date_begin: Date.parse(params[:booking][:date_begin].split(" au ").first),
      date_end: Date.parse(params[:booking][:date_begin].split(" au ").last)
    )
    @booking.developer = @developer
    @booking.user = current_user
    if @booking.save
      redirect_to user_profile_path(current_user)
    else
      render :new
    end
    authorize @booking
  end


  def accept
    @booking.status = "accepté"
    if @booking.save
      redirect_to user_profile_path(current_user)
    else
      render :new
    end
    authorize @booking
  end

  def refuse
    @booking.status = "refusé"
    if @booking.save
      redirect_to user_profile_path(current_user)
    else
      render :new
    end
    authorize @booking
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_developer
    @developer = Developer.find(params[:developer_id])
  end

  def booking_params
    params.require(:booking).permit(:date_begin, :date_end)
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  def index
    @query = params[:query]
    if @query.present?
      @developers = policy_scope(Developer).where("first_name ILIKE :query OR last_name ILIKE :query OR description ILIKE :query OR city ILIKE :query", query: "%#{@query}%")
    else
      @developers = policy_scope(Developer)
    end
    
  end

  def show
    authorize @developer
    @booking = Booking.new
    @review = Review.new
    @markers = [{
      lng: @developer.longitude,
      lat: @developer.latitude
    }]
  end

  def new
    @developer = Developer.new
    authorize @developer
  end

  def create
    @developer = Developer.new(developer_params)
    @developer.user = current_user
    if @developer.save
    redirect_to developer_path(@developer)
    else
      render :new
    end
    authorize @developer
  end

  def edit
    authorize @developer
  end

  def update
    authorize @developer
    if @developer.update!(developer_params)
      redirect_to developer_path(@developer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @developer.destroy
    redirect_to user_profile_path(current_user), status: :see_other
    authorize @developer
  end

  private

  def set_developer
    @developer = Developer.find(params[:id])
  end

  def developer_params
    params.require(:developer).permit(:first_name, :last_name, :description, :city, :image_url, :price_per_day, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def profile
    @user = current_user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_developer, only: [:index, :new, :create]

  def index
    @reviews = Review.where(developer_id: @developer)
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = Booking.find_by(user_id: current_user.id, developer_id: @developer.id)
    if @review.save
      redirect_to developer_path(@developer)
    else
      render 'developers/show', status: :unprocessable_entity
    end
    authorize @review
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_developer
    @developer = Developer.find(params[:developer_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/developers/_form.html.erb
<div class="form-container">
  <h3><strong>Ajouter</strong>-votre dev' !</h3><br>
  <%= simple_form_for @developer, html: { class: "formBloc" } do |f| %>

    <div class="formGroupe">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>

    <div class="formGroupe">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="formGroupe">
      <%= f.label :description, id: 'area' %>
      <%= f.text_area :description %>
    </div>

    <div class="formGroupe">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="formGroupe">
      <%= f.label :price_per_day %>
      <%= f.text_field :price_per_day %>
    </div>

    <div class="form">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="form-group d-flex justify-content-between pt-4">
      <%= link_to 'Annuler', developers_path, class: 'btn btn-danger'%>
      <%= f.submit "Ajoutez", class: 'btn custom-button' %>
    </div>
  <% end %>
</div>

app/views/developers/edit.html.erb
<%= render "form", list: @developer %>

app/views/developers/index.html.erb
  <div class="m-4">
    <% if @query.nil? || @query == "" %>
      <h3>Liste des Développeurs (<%= @developers.length %>)</h3>
    <% else %>
      <h3>Résultats de la recherche,</h3>
      <p>Mot clé : <strong><%= @query %></strong>. Nous trouvons <%= @developers.count %> developpeurs sur <%= Developer.count %> dans notre liste.</p>
    <% end %>
  </div>

  <div class="cards-grid">
    <% @developers.each do |developer| %>
      <%= link_to developer_path(developer) do %>
        <div class="developer-card">
          <% if !developer.image_url.nil? %>
            <%= image_tag(developer.image_url, alt: "developer picture", class: "image-style") %>
          <% else developer.photo.attached? %>
            <%= cl_image_tag developer.photo.key, alt: "developer picture" %>
          <% end %>
          <div class="developer-card-infos">
            <div class="d-flex justify-content-between align-items-center">
              <h1 class="developer-card-name">
                <%= developer.first_name %>
                <%= developer.last_name %>
              </h1>
              <h2 class="developer-card-pricing">
                <%= developer.price_per_day %>€/jour
              </h2>
            </div>
            <div class="developer-card-city">
              <p><i class="fa-solid fa-location-pin"></i> <%= developer.city %> </p>
            </div>
          </div>
          <span style="position: absolute; top: 10px; right: 15px; font-size: 20px; color: gold; text-shadow: 0 0 1px black;"><i style="font-size: 20px; color: gold;" class="fa-solid fa-star"></i> <%= developer.reviews.average(:rating).to_f.round %></span>
        </div>
     <% end %>
    <% end %>
  </div>

app/views/developers/new.html.erb
<%= render "form", list: @developer %>

app/views/developers/show.html.erb
<div class="show-container">

  <div class="show-container-top">
    <div class="developer-pictures">
      <% if !@developer.image_url.nil? %>
        <%= image_tag(@developer.image_url, alt: "developer picture", class: "image-style") %>
      <% else @developer.photo.attached? %>
        <%= cl_image_tag @developer.photo.key, alt: "developer picture" %>
      <% end %>
    </div>
    <div class="booking">
      <div class="developer-name">
          <%= @developer.first_name %> <%= @developer.last_name %> &nbsp;&nbsp;&nbsp;<span style="color: gold;"><i style="font-size: 35px;" class="fa-solid fa-star"></i> <%= @developer.reviews.average(:rating).to_f.round %></span>
          <p>Cette annonce est proposée par <%= @developer.user.first_name %> <%= @developer.user.last_name %></p>
      </div>
      <div class="developer-rate mt-5">
        <%= @developer.price_per_day %>€ par jour
      </div>
      <div class="booking-form" data-controller="flatpickr">
        <%= simple_form_for [@developer, @booking] do |f| %>
          <%= f.input :date_begin, as: :string, label: "Date de début", input_html: { data: { flatpickr_target: "dateBegin" }, id: 'date_begin' }%>
          <%= f.input :date_end, as: :string, label: "Date de fin", input_html: { data: { flatpickr_target: "dateEnd" }, id: 'date_end' } %>
          <%= f.button :submit, "Reserver", class: "mt-3 btn custom-button" %>
        <% end %>
      </div>
      <div class="d-flex justify-content-center gap-5 mt-5">
        <% if policy(@developer).edit? %>
        <%= link_to "Edit this developer", edit_developer_path(@developer) %>
        <% end %>
        <%= link_to "Delete this developer", @developer, data: { turbo_method: :delete, turbo_confirm: "Es tu sûre ?" } if policy(@developer).destroy? %>
      </div>
    </div>
  </div>

  <div class="show-container-bottom mt-4 border-bottom border-top pt-3 pb-3">
      <div class="description">
        <h2>Description :</h2>
        <p style="font-size: 25px;"><%= @developer.description %></p>
      </div>
  </div>

  <div class="show-container-informations mt-4 d-flex justify-content-between gap-5">
    <div class="review-container mb-4">
      <h2>Qu'avez vous pensé de <%= @developer.first_name %> ?</h2>

      <div class="form-review border-bottom mb-3 pb-3">
        <% if current_user.present? %>
          <% array = [] %>
          <% current_user.bookings.each do |booking| %>
            <% array << booking if booking.developer_id == @developer.id && booking.status == "accepté" %>
          <% end %>
          <% unless array.empty? %>
            <div class="form-container" id="review-form">
              <%= simple_form_for [@developer, @review], html: { class: "formBloc" }, url: developer_reviews_path(@developer) do |f| %>
                <div class="formGroupe">
                  <%= f.label :content %>
                  <%= f.text_field :content %>
                </div>
                <div class="formGroupe">
                  <%= f.label :rating %>
                  <%= f.input :rating, collection: [5, 4, 3, 2, 1, 0], selected: [5] %>
                </div>
                <%= f.submit "Ajoutez", class: 'btn custom-button' %>
              <% end %>
            </div>
          <% else %>
            <p><strong>Vous avez besoin d'une réservation pour laisser un avis.</strong></p>
          <% end %>
        <% else %>
          <p><strong>Connectez-vous pour laisser un avis.</strong></p>
        <% end %>
      </div>

      <div class="list-review">
        <h2 class="mb-5">Ils ont donné leur avis ! (<%= @developer.reviews.length %>)</h2>
        <% if @developer.reviews.empty? %>
          <p><strong>Aucun avis pour le moment, postez le votre !</strong></p>
        <% else %>
          <% @developer.reviews.first(5).each do |review| %>
            <div class="review-card">
              <div class="name">
                <%= review.booking.user.first_name %>
              </div>
              <div class="rating">
                <%= review.rating %>/5
              </div>
              <div class="content">
                <%= review.content %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="map-container mb-4">
      <h2>Ma localisation</h2>
      <div style="width: 100%; height: 100%;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dev-A-Licious</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;900&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/profile.html.erb
  <div class="profile-container d-flex">
    <div class="my-container-top">
      <div class="bloc-un">
        <div class="my-profile-container">
          <h1 class="border-bottom mb-5">Informations</h1>
            <p><strong>Prénom :</strong> <%= @user.first_name %></p><br>
            <p><strong>Nom :</strong> <%= @user.last_name %></p><br>
            <p><strong>Email :</strong> <%= @user.email %></p><br>
        </div>

        <div class="my-notifications-container">
          <h1 class="border-bottom">Notifications</h1>
          <% if current_user.developers.joins(:bookings).where(bookings: { status: "en attente" }).empty? %>
            <p>Aucune notification...</p>
          <% else %>
            <% current_user.developers.joins(:bookings).where(bookings: { status: "en attente" }).each do |dev| %>
              <% dev.bookings.where(status: "en attente").each do |booking| %>
                <div class="my-developers-card">
                  <div class="my-developers-card-infos">
                    <p>
                      <span><%= booking.user.first_name %> <%= booking.user.last_name %></span> a fait une demande de réservation pour
                      <span><%= dev.first_name %> <%= dev.last_name %></span></p>
                    <p>du <%= booking.date_begin %> au <%= booking.date_end %></p>
                    <p><strong><%= ((booking.date_end - booking.date_begin) * dev.price_per_day).to_i %> €</strong></p>
                  </div>
                  <div class="icons">
                    <%= button_to 'Accepter', accept_booking_path(booking.id), method: :patch, class: 'btn btn-accept' %>
                    <%= button_to 'Refuser', refuse_booking_path(booking.id), method: :patch, class: 'btn btn-refuse' %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="bloc-deux">
        <div class="my-bookings-container">
          <h1 class="border-bottom">Mes récentes réservations</h1>
          <% if current_user.developers.joins(:bookings).empty? %>
            <p>Aucune réservation en cours...</p>
          <% else %>
            <% @user.bookings.first(5).each do |booking| %>
              <div class="my-bookings-card border-bottom">
                <div class="info-booking">
                  <div class="picture">
                    <% if booking.developer.image_url %>
                      <%= image_tag(booking.developer.image_url, alt: "developer picture", class: "image-style") %>
                    <% else booking.developer.photo.attached? %>
                      <%= cl_image_tag(booking.developer.photo.key, alt: "developer picture") %>
                    <% end %>
                  </div>
                  <div class="my-bookings-card-infos">
                    <h2><%= booking.developer.first_name %> <%= booking.developer.last_name %></h2>
                    <p>Réservé.e du <%= booking.date_begin %> au <%= booking.date_end%></p>
                    <p><strong><%= ((booking.date_end - booking.date_begin) * booking.developer.price_per_day).to_i %> €</strong></p>
                  </div>
                </div>
                <% if booking.status == "en attente" %>
                  <div class="my-bookings-status bg-warning">
                    <p><%= booking.status%></p>
                  </div>
                <% elsif booking.status == "accepté" %>
                  <div class="my-bookings-status bg-success">
                    <p><%= booking.status%></p>
                  </div>
                <% else %>
                  <div class="my-bookings-status bg-danger">
                    <p><%= booking.status%></p>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="my-container-bottom">
      <div class="my-developers-container">
        <h1 class="border-bottom">Mes développeurs (<%= @user.developers.count %>)</h1>
        <div class="my-cards-grid">
          <% @user.developers.each do |dev| %>
            <div class="developer-card">
              <% if dev.image_url %>
                <%= image_tag(dev.image_url, alt: "developer picture", class: "image-style") %>
              <% else dev.photo.attached? %>
                <%= cl_image_tag(dev.photo.key, alt: "developer picture")%>
              <% end %>
              <div class="developers-card-infos">
                <h2><%= dev.first_name %> <%= dev.last_name %></h2>
              </div>
              <div class="icons">
                <%= link_to developer_path(dev.id), data: { turbo_method: :delete } do %>
                  <i class="fa-solid fa-trash"></i>
                <% end %>
                <%= link_to edit_developer_path(dev.id) do %>
                  <i class="fa-solid fa-pen-to-square" style="color: rgb(177, 156, 36);"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <a href="/">Dev-A-Licious</a>
  </div>

  <div class="search">
    <%= form_with url: developers_path, method: :get do |form| %>
      <%= form.text_field :query, placeholder: "Rechercher..." %>
      <button type="submit"><i class="fas fa-search"></i></button>
    <% end %>
  </div>

  <div class="call-to-action">
    <%= link_to "Ajoutez un dev", new_developer_path, id: "add" %>

    <% if current_user %>
      <div class="profile" data-controller="profile">
        <div style="width: 30px">
          <i class="fas fa-user" id="login" data-action="hover->profile#connect" data-profile-target="loginButton"></i>
        </div>
        <div class="profile-menu" data-profile-target="profileMenu">
          <%= link_to 'Mon profil', user_profile_path(current_user) %>
          <div class="separator"></div>
          <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete, turbo_action: "replace", turbo_frame: "user-menu" } %>
        </div>
      </div>
    <% else %>
      <div class="profile" data-controller="profile">
        <i class="fas fa-user" id="login" data-action="hover->profile#connect" data-profile-target="loginButton"></i>
        <div class="profile-menu" data-profile-target="profileMenu">
          <%= link_to "Login", new_user_session_path %>
          <div class="separator"></div>
          <%= link_to "S'inscrire", new_user_registration_path %>
        </div>
      </div>
    <% end %>
  </div>
</div>